
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-staff
owner: ucsb-cs156-f24
repo_name: team02-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-copyHelpRequest","number":70,"title":"Adding the Help Request Backend","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/70"},{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"aw-UCSBDiningCommonsMenuItemFormAndTests","number":69,"title":"Adding UCSB dining commons menu item form and tests","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/69"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Hongrui-UCSBOrganization","number":68,"title":"sh - Add fixtures for ucsbOrganization","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/68"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequests","number":66,"title":"jp - Copy existing CRUD API RecommendationRequest from team02","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/66"}]
